---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      profile: default
      region: us-east-1
  tasks:

    #########################################################################
    #########################################################################
    #############  Create public and private network acl  ###################
    #########################################################################
    #########################################################################

    - name: Create Private Network ACL
      ec2_vpc_nacl:
        vpc_id: "{{vpc.vpc.id}}"
        name: Module5-ig-private-acl
        subnets:
          - Module5-ig-private-sn-1
          - Module5-ig-private-sn-2
        tags:
          Name: Module5-ig-private-acl
        ingress:
          - [100, tcp, 'allow', '10.0.0.0/16', null, null, 5432, 5432]
          - [120, tcp, 'allow', '10.0.0.0/16', null, null, 443, 443]
          - [140, tcp, 'allow', '10.0.0.0/16', null, null, 1024, 65535]
        egress:
          - [120, tcp, 'allow', '10.0.0.0/16', null, null, 1024, 65535]
          - [130, tcp, 'allow', '10.0.0.0/16', null, null, 443, 443]
        state: present

    - name: Create Public Network ACL
      ec2_vpc_nacl:
        vpc_id: "{{vpc.vpc.id}}"
        name: Module5-ig-public-acl
        subnets:
          - Module5-ig-public-sn
        tags:
          Name: Module5-ig-public-acl
        ingress:
          - [100, tcp, 'allow', '141.152.26.111/32', null, null, 5000, 5000]
          - [125, tcp, 'allow', '24.196.25.139/32', null, null, 5000, 5000]
          - [150, tcp, 'allow', '24.239.105.213/32', null, null, 5000, 5000]
          - [175, tcp, 'allow', '141.152.26.111/32', null, null, 80, 80]
          - [180, tcp, 'allow', '24.196.25.139/32', null, null, 80, 80]
          - [185, tcp, 'allow', '24.239.105.213/32', null, null, 80, 80]
          - [200, tcp, 'allow', '0.0.0.0/0', null, null, 22, 22]
          - [300, tcp, 'allow', '0.0.0.0/0', null, null, 1024, 65535]
          - [400, tcp, 'allow', '141.152.26.111/32', null, null, 443, 443]
          - [425, tcp, 'allow', '24.196.25.139/32', null, null, 443, 443]
          - [450, tcp, 'allow', '24.239.105.213/32', null, null, 443, 443]
        egress:
          - [100, tcp, 'allow', '0.0.0.0/0', null, null, 80, 80]
          - [200, tcp, 'allow', '0.0.0.0/0', null, null, 443, 443]
          - [300, tcp, 'allow', '0.0.0.0/0', null, null, 1024, 65535]
        state: present