---
- hosts: localhost
  gather_facts: yes
  vars:
    ami_id: "ami-09d95fab7fff3776c"
  module_defaults:
    group/aws:
      profile: default
      region: us-east-1

  tasks:
    - name: Provision EC2 instance
      ec2:
        key_name: csKP
        group:
          - Module5-ig-nginx-server-sg
          - Module5-ig-postgres-tag-sg
          - Module5-ig-endpoint-tag-sg
        instance_type: t3a.nano
        image: "{{ami_id}}"
        instance_tags:
          Name: Module5 EC2 DB Setup
        wait: yes
        wait_timeout: 500
        vpc_subnet_id: "{{public_subnet.subnet.id}}"
        instance_profile_name: image-gallery-server-role
        assign_public_ip: yes
        user_data: "{{ lookup('file', './startup-scripts/ansible_startup.sh') }}"
        exact_count: 1
        count_tag:
          Name: Module5 EC2 DB Setup
      register: ec2_dev

    - name: Add dev ec2 host to hosts list
      add_host:
        name: "{{ec2_dev.tagged_instances[0].public_ip}}"
        groups: bastion
        rds_address: "{{image_gallery_db.instance.endpoint}}"
        #hostname: Module5 EC2 DB Setup
        #groups: db_setup_ec2