---
- hosts: localhost
  gather_facts: no
  module_defaults:
    group/aws:
      #profile: default
      region: us-east-1
  tasks:

    #########################################################################
    #########################################################################
    #############  Create VPC, Subnets, IGW and NAT  ########################
    #########################################################################
    #########################################################################

    - name: Create VPC
      ec2_vpc_net:
        name: image-gallery-ansible
        cidr_block: 10.0.0.0/16
        tags:
          Module: 5
        state: present
      register: vpc

    - name: Create Public Subnet
      ec2_vpc_subnet:
        vpc_id: "{{vpc.vpc.id}}"
        az: us-east-1a
        tags:
          Name: Module5-ig-public-sn
          Module: 5
        cidr: 10.0.1.0/24
        state: present
      register: public_subnet

    - name: Create Private Subnet 1
      ec2_vpc_subnet:
        vpc_id: "{{vpc.vpc.id}}"
        az: us-east-1a
        tags:
          Name: Module5-ig-private-sn-1
          Module: 5
        cidr: 10.0.2.0/24
        state: present
      register: private_subnet1

    - name: Create Private Subnet 2
      ec2_vpc_subnet:
        vpc_id: "{{vpc.vpc.id}}"
        az: us-east-1b
        tags:
          Name: Module5-ig-private-sn-2
          Module: 5
        cidr: 10.0.3.0/24
        state: present
      register: private_subnet2

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc.vpc.id}}"
        state: present
        tags:
          Name: Module5 igw
      register: igw

    - name: Create NAT Gateway
      ec2_vpc_nat_gateway:
        eip_address: 3.226.156.250
        subnet_id: "{{public_subnet.subnet.id}}"
        state: present
        wait: yes
      register: nat

    - name: Create Public Route Table
      ec2_vpc_route_table:
        vpc_id: "{{vpc.vpc.id}}"
        tags:
          Name: Module5 Public Route Table
        subnets:
          - "{{public_subnet.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{igw.gateway_id}}"
        state: present

    - name: Create Private Route Table
      ec2_vpc_route_table:
        vpc_id: "{{vpc.vpc.id}}"
        tags:
          Name: Module5 Private Route Table
        subnets:
          - "{{private_subnet1.subnet.id}}"
          - "{{private_subnet2.subnet.id}}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{nat.nat_gateway_id}}"
        state: present