---
- hosts: bastion
  gather_facts: no
  module_defaults:
    group/aws:
      profile: default
      region: us-east-1
  vars:
    host_name: "{{image_gallery_db.instance.endpoint}}"

  tasks:
    - name: debug
      debug:
        var: host_name
    - name: Create image_gallery database
      postgresql_db:
        name: image_gallery
        login_host: module5-image-gallery.cyoqs8hmumyv.us-east-1.rds.amazonaws.com
        login_user: postgres
        login_password: Keldailin120217!
        state: present

    - name: Create Image Gallery User
      postgresql_user:
        db: image_gallery
        #login_host: "{{image_gallery_db.instance.endpoint}}"
        login_host: module5-image-gallery.cyoqs8hmumyv.us-east-1.rds.amazonaws.com
        login_user: postgres
        login_password: Keldailin120217!
        name: image_gallery
        password: Keldailin120217!
        priv: ALL
        role_attr_flags: INHERIT
        no_password_changes: yes

    - name: Add db credentials as secret
      aws_secret:
        name: Module5-image-gallery-secret
        secret_type: string
        secret: '{"username": "image_gallery", "password": "Keldailin120217!", "host": "module5-image-gallery.cyoqs8hmumyv.us-east-1.rds.amazonaws.com", "database_name": "image_gallery"}'
        state: present
      register: secret_facts

    - name: Create Users Table
      postgresql_table:
        db: image_gallery
        #db: "{{image_gallery_db.instance.db_name}}"
        login_host: module5-image-gallery.cyoqs8hmumyv.us-east-1.rds.amazonaws.com
        login_user: image_gallery
        login_password: Keldailin120217!
        table: users
        columns:
          - username TEXT PRIMARY KEY NOT NULL
          - password TEXT
          - full_name TEXT